### ISSUE TITLE
IllegalArgumentException: Tried to display dialog for unknown preference type.

### ISSUE THREAD

**Issue by ligi** [Kunzisoft/AndroidClearChroma#15]
When trying out the library and using it regarding the README I get the following exception when clicking on the preference:

```
 java.lang.IllegalArgumentException: Tried to display dialog for unknown preference type. Did you forget to override onDisplayPreferenceDialog()?
        at android.support.v7.preference.PreferenceFragmentCompat.onDisplayPreferenceDialog(PreferenceFragmentCompat.java:654)
        at android.support.v7.preference.PreferenceManager.showDialog(PreferenceManager.java:552)
        at com.kunzisoft.androidclearchroma.ChromaPreferenceCompat.onClick(ChromaPreferenceCompat.java:207)
        at android.support.v7.preference.Preference.performClick(Preference.java:1163)
        at android.support.v7.preference.Preference.performClick(Preference.java:1148)
        at android.support.v7.preference.Preference$1.onClick(Preference.java:172)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ligi** [comment]
ok this can be fixed ChromaPreferenceFragmentCompat instead of PreferenceFragmentCompat - somehow I do not read the README like this - so this issue might be closed or taken as a need for the README to be improved.

**Comment by J-Jamet** [comment]
OK, I change the Readme a bit.
